### PR TITLE
append code(object->category) for lgb(categorical features)

### PR DESCRIPTION
**Pull request by sungreong**
What does this PR do?
=====================
In Lightgbm, an error was found and resolved when applying a category features.

References
==========
https://medium.com/swlh/dealing-with-categorical-variables-in-machine-learning-4401b949b093

Testing performed
=================
I tested it and found it to work.

Known issues
============

### CODE REVIEW

**Comment by Ekeany** [comment]
Hi,

Thanks for the Pull Request. Your commit has -1,1032 lines deleted +1,1039 added so the Files Changed tab is useless could you point me to 7 lines of code that you have changed.

Thanks

**Comment by sungreong** [comment]
Hi :)

I'm not familiar with it, so I guess this happened by copying and pasting the entire code.

I confirmed that when permutation in the code, the category type changes back to the object type.
So I added the code below to improve these areas.


```
## In create_shadow_features 

        # append
        obj_col = self.X_shadow.select_dtypes("object").columns.tolist()
        if obj_col ==[] :
             pass
        else :
             self.X_shadow[obj_col] =self.X_shadow[obj_col].astype("category")
```

**Comment by yair4Data** [comment]
hi ,
when is this version is due to get into pypi ?
thanks

**Comment by Ekeany** [comment]
Hi,

It is already on the pypi artifactory it was updated a few months ago.

**Comment by yair4Data** [comment]
is version 1.0.14 includes the fix ? i see that it is from Sep 27 , it's before the commit , isn't it ?

[https://pypi.org/project/BorutaShap/](url)

**Comment by Ekeany** [comment]
Hi,

I have pushed the latest code to the artifactory just now version 1.0.15.

https://pypi.org/project/BorutaShap/

Let me know if you face any issues

**Comment by yair4Data** [comment]
thanks @Ekeany  , yes, it did the job.
additional question - do i need to give to borutaShap just the base model (in this case LGBM) or does it worth trying to do hyperParameter tuning , will it change the relevant features , or just give better performance?

**Comment by sungreong** [comment]
Hello. I think this code is necessary for certain algorithms (lightgbm, catboost) that deal with category variables.
This is because, while copying data from this package, we found a phenomenon in which the category column type changes from category to object.
So, this part is the modified code.

**Comment by Ekeany** [comment]
That is a great question. In my opinion feature selection is a
preprocessing step  therefore, I would run the base hyperparameters and
then tune my model to the subset of features provided by the base model.

Sorry for the late reply.

**Pull request merged**
